#include <math.h>
#include <stdio.h>
#include <stdlib.h>

// gcc 012-highly-divisible-triangular-number.c -lm

// https://projecteuler.net/problem=12
// The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
// 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
// Let us list the factors of the first seven triangle numbers:
//  1: 1
//  3: 1,3
//  6: 1,2,3,6
// 10: 1,2,5,10
// 15: 1,3,5,15
// 21: 1,3,7,21
// 28: 1,2,4,7,14,28
// We can see that 28 is the first triangle number to have over five divisors.
// What is the value of the first triangle number to have over five hundred divisors?

int factorsOfN(int n) {
	int factors = 1;
	double sqrtN = sqrt(n);
	int n2 = (int) sqrtN;

	for (int i = 1; i <= n2; i++) {
		if (n % i == 0) {
			factors++;
		}
	}

	factors *= 2;

	if (sqrtN == n2) {
		factors--;
	}

	return factors;
}

void main() {
	int number = 0;
	int maxFactors = 0;
	int factors;

	for (int i = 0; 1; i++) {
		number += i;
		factors = factorsOfN(number);

		if (factors > maxFactors) {
			maxFactors = factors;
			printf("%i %i\033[0m\033[0K\n", number, factors);
		}

		if (factors > 500) {
			break;
		}
	}
}
